
spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://root:Adm!n123$@localhost:27017/product-service?authSource=admin
server:
  port: 1662

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs